server:
  port: 8082

fraudLevel: 3000

fullView: false

payments:
  src: file
  file:
    skip_first: false
    name: payment_src.csv

paystack:
  src: file
  file:
    name: payment_paystack.csv
    date_pattern: yyyy-MM-dd HH:mm:ss
    fields: 0,1,2,3,4
    updates:
      skip_first: true
      prefix: payment_paystack.csv.
      date_pattern: MMM dd, yyyy h:mm:ss a
      fields: 0,2,3,-1,1
      suffices: _2017031020
  rest:
    hostname: api.paystack.co
    port: 443
    secret_key_name: paystack_key_live

output: file
output_file_name: paystack_fraud_output.csv
